### PR TITLE
add git tag create and delete

### PR DESCRIPTION
**Pull request by of-many-devices**
add git tag create and delete

### CODE REVIEW

**Comment by tonytamsf** [comment]
@of-many-devices Can you add some tests please

**Comment by tonytamsf** [comment]
@of-many-devices bump, can you add some tests?

**Comment by of-many-devices** [comment]
Yep, sorry. Been busy, will look at adding some tests ASAP. :)

**Comment by of-many-devices** [comment]
Hi Tony,

	Can you point at where to start with tests?
	I was hoping to cut-paste-amend existing tests for functionality I've added but there doesn't seem to be much existing test infrastructure?
	The tests directory currently contains almost nothing?
	What am I missing?

BW
David.O.

**Pull request merged**
