### PR TITLE
Adding build notification support.

### PR DESCRIPTION
**Pull request by Jerhaad**

### CODE REVIEW

**Comment by cosmin** [comment]
Build failed in Travis for Python 3.3. Is that still a version we want to support?

**Comment by Jerhaad** [comment]
I would prefer not to, but I think it is still possible to support.

**Comment by Jerhaad** [comment]
That is your call.  I just wanted to use the Enum class to enforce Build Status strings.  I can find another way to do this if necessary.

**Comment by ellinorcrux** [comment]
Any updates? I'm interested in using this feature :)

**Pull request merged**
